networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    # volumes:
    #   - './nginx.conf:/etc/nginx/nginx.conf'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dev

  backend:
    build: 
      context: ./backend
    networks:
      - dev

  frontend:
    build: 
      context: ./frontend
    networks:
      - dev

